const FRAUD_TYPES = Object.freeze({ part_time_scam: "刷单返利诈骗", impersonate_public: "冒充公检法诈骗", fake_loan: "虚假贷款诈骗", fake_refund: "冒充客服退款", other: "其他诈骗" });
const RISKS = Object.freeze({ low: "低风险", medium: "中风险", high: "高风险" });
const STATUSES = Object.freeze({ pending_counselor_verify: "待辅导员核验", pending_security_verify: "待保卫处核验", in_process: "处理中", closed: "已结案" });
const OUTCOMES = Object.freeze({ loss_confirmed: "已确认损失", loss_no_loss: "未确认损失", misreport: "误报", consultation: "咨询" });
function dateText(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString(); }
function viewOf(report = {}) { return { ...report, fraudTypeText: FRAUD_TYPES[report.fraudType] || "未知诈骗类型", riskText: RISKS[report.riskLevel] || "风险待评估", statusText: STATUSES[report.status] || "状态待更新", outcomeText: OUTCOMES[report.finalOutcome] || "—", incidentAtText: dateText(report.incidentAt), submittedAtText: dateText(report.submittedAt), closedAtText: dateText(report.closedAt), isClosed: report.status === "closed", hasConfirmedLoss: typeof report.confirmedLossAmount === "number" }; }
const pageDefinition = { data: { report: null, loading: true, errorMessage: "" }, onLoad(query) { this.reportId = typeof query.reportId === "string" ? query.reportId : ""; this.loadDetail(); }, async loadDetail() { if (!this.reportId) { this.setData({ loading:false, errorMessage:"工单编号无效。" }); return; } this.setData({ loading:true, errorMessage:"" }); try { const response=await wx.cloud.callFunction({name:"getStudentReportDetail",data:{reportId:this.reportId}}); const result=response.result||{}; if (!result.ok || !result.report) { this.setData({report:null,errorMessage:"工单详情暂时无法加载。"}); return; } this.setData({report:viewOf(result.report)}); } catch(error) { this.setData({report:null,errorMessage:"工单详情暂时无法加载。"}); } finally {this.setData({loading:false});} } };
Page(pageDefinition);
if (typeof module !== "undefined") module.exports={__testables:{STATUSES,OUTCOMES,pageDefinition,viewOf}};
